from docx import Document
from docx.shared import Pt,RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
p=r'C:\\xampp\\htdocs\\Taxguard\\TaxGuard_User_Manual.docx'
d=Document(); s=d.styles['Normal'];s.font.name='Aptos';s.font.size=Pt(11);s.font.color.rgb=RGBColor(35,48,65)
for n,z in [('Title',28),('Heading 1',19),('Heading 2',13)]:
 st=d.styles[n];st.font.name='Aptos';st.font.size=Pt(z);st.font.bold=True;st.font.color.rgb=RGBColor(11,39,67)
d.add_paragraph('TaxGuard System Process Manual',style='Title')
d.add_paragraph('How the company records clients, deadlines, and filings')
x=d.add_paragraph();x.add_run('Purpose. ').bold=True;x.add_run('This guide explains the day-to-day workflow in TaxGuard. TaxGuard records filing activity after a return is submitted through the company’s normal external filing channel.')
def h(t,l=1):d.add_heading(t,l)
def n(t):d.add_paragraph(t,style='List Number')
def b(t):d.add_paragraph(t,style='List Bullet')
h('The system process');d.add_paragraph('Client setup creates the master record. Required forms determine the obligations. Deadline references provide periods and due dates. The compliance tracker shows what is incomplete, overdue, or complete. Recording a submission updates the tracker and dashboard.')
h('1  Create a client')
d.add_paragraph('Open Client directory and choose Add client. Enter the client name, TIN, start of filing date, business type, tax type, and status. Select every required form; selected forms appear as pills. Add remarks if needed, then choose Save client.')
d.add_paragraph('The TIN must use 000-000-000-000 format and be unique. Required values and dates are validated before saving.')
h('2  Review or edit a client')
d.add_paragraph('Search Client directory by client name or TIN. Click a row to open the client details. Choose Edit inside the detail window, update the values, and save. Changing required forms changes the client’s generated obligations.')
h('3  Set deadline references')
d.add_paragraph('Open Deadline reference to review a form’s periods and due dates.')
for t in ['Choose Add deadline to create a schedule reference.','Open an existing form and choose Edit schedule to change dates.','Confirm the periods and dates, then choose Save schedule.']:n(t)
d.add_paragraph('Existing values are loaded into the editor. Verify dates against current company filing guidance before relying on them.')
h('4  Review obligations')
d.add_paragraph('Open Compliance tracker and select a tax year. Each selected form is expanded into periods such as Q1, Q2, Q3, Q4, months, or Annual. Search by client or form and filter by status or period.')
for t in ['Incomplete means no filing has been recorded.','Overdue means the obligation is incomplete and past its due date according to the system date.','Complete means a filing record has been saved.']:b(t)
h('5  Record a filing')
d.add_paragraph('Record the filing after the company submits the return outside TaxGuard.')
for t in ['Find the client, form, and period.','Choose Record filing.','Enter the actual filing date.','Enter the confirmation or reference number.','Add optional remarks and choose Save filing.']:n(t)
d.add_paragraph('The confirmation/reference number is currently required. After saving, the obligation becomes Complete and appears in Recent filings.')
h('6  Review a filing')
d.add_paragraph('Choose View filing on a completed obligation to review its filing date, reference number, and remarks. Use the available edit action to correct a saved filing, then save again.')
h('7  Use the dashboard')
d.add_paragraph('Overview summarizes the selected year. Clients in this year counts applicable clients. Filings completed counts saved submissions. Awaiting filing shows remaining work. Overdue obligations shows incomplete work past due. Filing progress by form and Portfolio completion show progress across the workspace. Recent filings lists the latest submissions.')
d.add_paragraph('Clicking a recent filing opens Client directory with that client filtered and the client detail window open.')
h('8  Recommended routine')
for t in ['Keep each client’s master information and required forms current.','Review deadline references before the filing period.','Check Compliance tracker regularly for incomplete and overdue work.','Record each submission immediately after filing.','Use Recent filings and dashboard totals to find missing records.']:b(t)
h('What TaxGuard does not do')
d.add_paragraph('TaxGuard does not prepare, transmit, or verify returns with BIR. It records the company’s filing activity and calculates status from client assignments, schedule dates, and saved filing records.')
d.add_paragraph('TaxGuard · Integrated multi-year compliance monitoring').alignment=WD_ALIGN_PARAGRAPH.CENTER
d.save(p);print(p)
