module.exports=async function(win,root){
  win.webContents.setBackgroundThrottling(false);
  await win.webContents.executeJavaScript('('+async function(){
    attemptLogin('admin','taxguard2026');
    await new Promise(r=>setTimeout(r,550));
    if(!document.body.classList.contains('logged-in'))throw Error('Login failed');
    year=2026;go('clients');editClient();
    let f=document.querySelector('#client-form');
    f.elements.name.value='Allocation test';f.elements.tin.value='111-222-333-000';f.elements.start.value='2025-01-01';
    f.elements.calendar.value='calendar';f.elements.income.value='eight';
    f.elements.compensation.value='no';f.elements.expanded.value='yes';
    document.querySelector('#suggest-client-forms').click();
    if(f.querySelector('[value="1701-Q"]').checked)throw Error('Applied before review');
    document.querySelector('#apply-client-forms').click();
    if(!f.querySelector('[value="1701A"]').checked||f.querySelector('[value="2551-Q"]').checked)throw Error('Incorrect 8% allocation');
    f.requestSubmit();await new Promise(r=>setTimeout(r,240));
    const c=state.clients[0];
    if(!c)throw Error('Client not saved');
    if(obligations().filter(o=>o.f.id==='0619-E').length!==8)throw Error('Wrong withholding periods');
    if(!getClientsReportData().rows[0][7].includes('1701A'))throw Error('Report uses old forms');
    year=2025;
    if(obligations().length)throw Error('Allocation leaked into prior year');
    year=2027;
    if(obligations().length)throw Error('Election leaked into future year');
    year=2026;go('tracker');fileModal(c.id+':2026:1701-Q:Q1');
    f=document.querySelector('#filing-form');
    f.elements.date.value='2026-05-15';f.elements.reference.value='TEST';
    f.requestSubmit();await new Promise(r=>setTimeout(r,240));
    go('clients');editClient(c.id);
    f=document.querySelector('#client-form');
    if(!f.querySelector('[value="1701-Q"]').disabled)throw Error('Filed form not protected');
    f.elements.name.value='Cancelled';
    document.querySelector('#cancel').click();await new Promise(r=>setTimeout(r,240));
    if(state.clients[0].name==='Cancelled')throw Error('Cancelled edit saved');
    editClient(c.id);
    await new Promise(r=>setTimeout(r,240));
    document.querySelector('#suggest-client-forms').scrollIntoView({block:'center'});
    await new Promise(r=>setTimeout(r,100));
    if(!document.querySelector('#modal').open)throw Error('Client editor closed unexpectedly');
  }.toString()+')()');
  const fs=require('node:fs'),path=require('node:path');
  const screenshot=path.join(require('node:os').tmpdir(),'taxguard-allocation-preview.png');
  fs.writeFileSync(screenshot,(await win.webContents.capturePage()).toPNG());
  console.log('Allocation preview: '+screenshot);
  await win.loadFile(path.join(root,'index.html'));
  await win.webContents.executeJavaScript('('+function(){
    year=2026;
    if(obligations().filter(o=>o.f.id==='0619-E').length!==8)throw Error('Allocation lost on reload');
    if(!state.filings[state.clients[0].id+':2026:1701-Q:Q1'])throw Error('Filing lost');
  }.toString()+')()');
  console.log('ALLOCATION DESKTOP PASS');
};
