module.exports=async function(win,root){
  win.webContents.setBackgroundThrottling(false);
  await win.webContents.executeJavaScript('('+async function(){
    attemptLogin('admin','taxguard2026');
    await new Promise(r=>setTimeout(r,550));
    if(!document.body.classList.contains('logged-in'))throw Error('Login failed');
    year=2026;go('clients');editClient();
    let f=document.querySelector('#client-form');
    f.elements.name.value='Allocation test';f.elements.tin.value='111-222-333-000';f.elements.start.value='2025-01-01';
    f.elements.calendar.value='calendar';f.elements.income.value='eight';
    f.elements.compensation.value='no';f.elements.expanded.value='yes';
    document.querySelector('#suggest-client-forms').click();
    if(f.querySelector('[value="1701-Q"]').checked)throw Error('Applied before review');
    document.querySelector('#apply-client-forms').click();
    if(!f.querySelector('[value="1701A"]').checked||f.querySelector('[value="2551-Q"]').checked)throw Error('Incorrect 8% allocation');
    if(!document.querySelector('#client-form-pills').textContent.includes('1701A'))throw Error('Suggestions did not update pills');
    document.querySelector('#select-client-forms').click();
    let picker=document.querySelector('.client-forms-dialog');
    if(!picker.open)throw Error('Form picker did not open');
    picker.querySelector('[value="1601-C"]').checked=true;
    picker.querySelector('.picker-cancel').click();
    await new Promise(r=>setTimeout(r,50));
    if(f.querySelector('[value="1601-C"]').checked)throw Error('Cancelled selection applied');
    document.querySelector('#select-client-forms').click();
    picker=document.querySelector('.client-forms-dialog');
    picker.querySelector('[value="1601-C"]').checked=true;
    picker.querySelector('.picker-done').click();
    await new Promise(r=>setTimeout(r,50));
    const remove=document.querySelector('#client-form-pills [aria-label="Remove 1601-C"]');
    if(!remove)throw Error('Selected form pill missing');
    remove.click();
    if(f.querySelector('[value="1601-C"]').checked)throw Error('Pill removal did not update selection');
    f.requestSubmit();await new Promise(r=>setTimeout(r,240));
    const c=state.clients[0];
    if(!c)throw Error('Client not saved');
    if(obligations().filter(o=>o.f.id==='0619-E').length!==8)throw Error('Wrong withholding periods');
    if(!getClientsReportData().rows[0][7].includes('1701A'))throw Error('Report uses old forms');
    year=2025;
    if(obligations().length)throw Error('Allocation leaked into prior year');
    year=2027;
    if(obligations().some(o=>o.f.id==='1701A'))throw Error('Election leaked into future year');
    year=2026;go('clients');clientModal(c.id);
    document.querySelector('#record-client-filing').click();
    const selectionLayer=document.querySelector('#modal'),clientLayer=selectionLayer.workspaceParent;
    if(!clientLayer?.open||!clientLayer.querySelector('#client-year-history'))throw Error('Filing selection replaced client details');
    document.querySelector('#client-filing-period').value=c.id+':2026:1701-Q:Q1';
    document.querySelector('#choose-client-filing').requestSubmit();
    if(document.querySelector('#modal').workspaceParent!==selectionLayer||!selectionLayer.open)throw Error('Filing form replaced selection');
    f=document.querySelector('#filing-form');
    f.elements.date.value='2026-05-15';f.elements.reference.value='TEST';
    f.requestSubmit();
    if(state.filings[c.id+':2026:1701-Q:Q1'])throw Error('Filing saved before confirmation');
    if(!document.querySelector('#filing-confirmation').textContent.includes('TEST'))throw Error('Confirmation details missing');
    if(!clientLayer.open||!selectionLayer.open||!document.querySelector('#modal').open)throw Error('Confirmation closed earlier layers');
    document.querySelector('#back-to-filing').click();
    await new Promise(r=>setTimeout(r,50));
    if(f.elements.reference.value!=='TEST')throw Error('Back to edit lost draft');
    f.requestSubmit();
    document.querySelector('#confirm-save-filing').click();
    await new Promise(r=>setTimeout(r,240));
    if(!state.filings[c.id+':2026:1701-Q:Q1'])throw Error('Confirmed filing not saved');
    if(!document.querySelector('#record-client-filing'))throw Error('Client details not restored');
    editClient(c.id);
    f=document.querySelector('#client-form');
    if(!f.querySelector('[value="1701-Q"]').disabled)throw Error('Filed form not protected');
    if(document.querySelector('#client-form-pills [aria-label="Remove 1701-Q"]'))throw Error('Filed pill removable');
    document.querySelector('#select-client-forms').click();
    picker=document.querySelector('.client-forms-dialog[open]');
    if(!picker||!picker.querySelector('[value="1701-Q"]').disabled)throw Error('Popup state '+JSON.stringify([...document.querySelectorAll('.client-forms-dialog')].map(d=>({open:d.open,disabled:d.querySelector('[value="1701-Q"]')?.disabled}))));
    picker.querySelector('.picker-done').click();
    await new Promise(r=>setTimeout(r,50));
    f.elements.name.value='Cancelled';
    document.querySelector('#cancel').click();await new Promise(r=>setTimeout(r,240));
    if(state.clients[0].name==='Cancelled')throw Error('Cancelled edit saved');
    editClient(c.id);
    await new Promise(r=>setTimeout(r,240));
    if(!document.querySelector('#suggest-client-forms'))throw Error('Missing editor '+JSON.stringify([...document.querySelectorAll('dialog')].map(d=>({id:d.id,open:d.open,title:d.querySelector('h2')?.textContent}))));
    document.querySelector('#suggest-client-forms').scrollIntoView({block:'center'});
    await new Promise(r=>setTimeout(r,100));
    if(!document.querySelector('#modal').open)throw Error('Client editor closed unexpectedly');
  }.toString()+')()');
  const fs=require('node:fs'),path=require('node:path');
  const screenshot=path.join(require('node:os').tmpdir(),'taxguard-allocation-preview.png');
  fs.writeFileSync(screenshot,(await win.webContents.capturePage()).toPNG());
  console.log('Allocation preview: '+screenshot);
  await win.loadFile(path.join(root,'index.html'));
  await win.webContents.executeJavaScript('('+function(){
    year=2026;
    if(obligations().filter(o=>o.f.id==='0619-E').length!==8)throw Error('Allocation lost on reload');
    if(!state.filings[state.clients[0].id+':2026:1701-Q:Q1'])throw Error('Filing lost');
  }.toString()+')()');
  console.log('ALLOCATION DESKTOP PASS');
  await win.webContents.executeJavaScript('('+async function(){
    year=2027;go('clients');
    const profile=state.clients[0].yearProfiles[2027];
    if(!profile||!profile.reviewReason||profile.income!=='unknown')throw Error('Automatic year or election review missing');
    if(profile.forms.includes('1701A'))throw Error('Annual election carried unchanged');
    if(!profile.forms.includes('0619-E'))throw Error('Recurring withholding missing');
    if(obligations().some(o=>o.filing))throw Error('Source filings copied');
    const saved=JSON.stringify(profile);render();
    if(JSON.stringify(state.clients[0].yearProfiles[2027])!==saved)throw Error('Existing target changed');
    clientModal(state.clients[0].id);document.querySelector('#client-year-history').click();
    const parent=document.querySelector('#modal'),originalDetails=parent.innerHTML;
    if(!parent.open||!parent.querySelector('#record-client-filing')||!document.querySelector('#year-history-dialog')?.open)throw Error('History replaced parent dialog');
    document.querySelector('#back-history').click();
    if(!parent.open||parent.innerHTML!==originalDetails||document.querySelector('#year-history-dialog'))throw Error('Back did not preserve client details');
    document.querySelector('#client-year-history').click();
    document.querySelector('#year-history-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));
    if(!parent.open||document.querySelector('#year-history-dialog')||year!==2027)throw Error('Escape did not preserve client details');
    document.querySelector('#client-year-history').click();
    document.querySelector('[data-history-year="2026"]').click();
    if(document.querySelector('#year-history-dialog')||!parent.open)throw Error('Year selection did not restore parent');
    if(year!==2026||!obligations().some(o=>o.filing))throw Error('History lost original filing');
    document.querySelector('#close-client').click();await new Promise(r=>setTimeout(r,240));
  }.toString()+')()');
  console.log('ROLLOVER DESKTOP PASS');
  await win.webContents.executeJavaScript('('+async function(){
    const outside=()=>{
      document.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,button:0,clientX:-1,clientY:-1}));
      document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,button:0,clientX:-1,clientY:-1}));
    };
    const tick=()=>new Promise(r=>setTimeout(r,80));
    go('clients');clientModal(state.clients[0].id);
    outside();await tick();
    if(document.querySelector('#modal').open)throw Error('Clean popup stayed open');
    editClient(state.clients[0].id);
    const parent=document.querySelector('#modal'),name=parent.querySelector('[name="name"]'),original=name.value;
    name.value='Unsaved outside test';
    outside();
    if(!parent.open||!document.querySelector('#discard-dialog')?.open)throw Error('Dirty popup closed without warning');
    document.querySelector('#keep-editing').click();await tick();
    if(name.value!=='Unsaved outside test'||!parent.open)throw Error('Keep editing lost draft');
    name.value=original;
    outside();await tick();
    if(parent.open||document.querySelector('#discard-dialog'))throw Error('Reverted change still warned');
    editClient(state.clients[0].id);
    document.querySelector('#select-client-forms').click();
    const picker=document.querySelector('.client-forms-dialog[open]');
    const option=picker.querySelector('input:not(:disabled)');option.checked=!option.checked;
    outside();
    if(!picker.open||!document.querySelector('#discard-dialog'))throw Error('Changed picker did not warn');
    document.querySelector('#discard-changes').click();await tick();
    if(picker.isConnected||!parent.open)throw Error('Discard did not close only top popup');
    parent.querySelector('[name="name"]').value='Discard me';
    outside();document.querySelector('#discard-changes').click();await tick();
    if(parent.open||state.clients[0].name==='Discard me')throw Error('Discard saved changes');
  }.toString()+')()');
  console.log('DIALOG DISMISS PASS');
  await win.webContents.executeJavaScript('('+async function(){
    for(const dialog of [...document.querySelectorAll('dialog[open]')].reverse())dialog.close();
    await new Promise(r=>setTimeout(r,100));
    go('clients');clientModal(state.clients[0].id);
    const client=document.querySelector('#modal');
    client.querySelector('#edit-client-detail').click();
    const editor=document.querySelector('#modal');
    if(editor===client||!client.open||editor.workspaceParent!==client)throw Error('Edit client did not stack');
    editor.querySelector('#cancel').click();await new Promise(r=>setTimeout(r,240));
    if(!client.open||document.querySelector('#modal')!==client)throw Error('Editor cancel lost client details');
    client.close();
    go('deadlines');deadlineModal('1701-Q');
    const schedule=document.querySelector('#modal');schedule.querySelector('#edit-schedule').click();
    if(!schedule.open||document.querySelector('#modal').workspaceParent!==schedule)throw Error('Schedule editor did not stack');
    document.querySelector('#cancel-edit').click();await new Promise(r=>setTimeout(r,100));
    if(!schedule.open||document.querySelector('#modal')!==schedule)throw Error('Schedule cancel lost details');
    schedule.close();
    go('settings');openUserAccountModal();
    const account=document.querySelector('#modal');
    confirmCreateUser({username:'stack-test',company_name:'Test',role:'Staff',is_active:1,password:'test1234'});
    if(!account.open||document.querySelector('#modal').workspaceParent!==account)throw Error('Account confirmation did not stack');
    document.querySelector('#btn-back-create-user').click();await new Promise(r=>setTimeout(r,100));
    if(document.querySelector('#modal')!==account||!account.open)throw Error('Account back lost draft');
    account.close();
  }.toString()+')()');
  console.log('STACKED WORKSPACE DIALOGS PASS');
};
